Fixes #28521 - log location, pre/post, dynamic layout
Co-authored-by: Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl>

diff --git a/app/views/unattended/provisioning_templates/provision/atomic_kickstart_default.erb b/app/views/unattended/provisioning_templates/provision/atomic_kickstart_default.erb
--- a/app/views/unattended/provisioning_templates/provision/atomic_kickstart_default.erb
+++ b/app/views/unattended/provisioning_templates/provision/atomic_kickstart_default.erb
@@ -3,6 +3,12 @@ kind: provision
 name: Atomic Kickstart default
 model: ProvisioningTemplate
 %>
+<%
+  rhel_compatible = @host.operatingsystem.family == 'Redhat' && @host.operatingsystem.name != 'Fedora'
+  is_fedora = @host.operatingsystem.name == 'Fedora'
+  os_major = @host.operatingsystem.major.to_i
+  os_minor = @host.operatingsystem.minor.to_i
+-%>
 
 lang <%= host_param('lang') || 'en_US.UTF-8' %>
 keyboard <%= host_param('keyboard') || 'us' %>
@@ -42,16 +48,51 @@ rootpw --iscrypted <%= root_pass %>
 
 reboot
 
+<% if @dynamic -%>
+# Partition table dynamic generation
+%pre --log=/tmp/install.pre.dynamic.log
+<%= @host.diskLayout %>
+%end
+<% end -%>
+
+%pre --log=/tmp/install.pre.custom.log
+# Custom pre snippet generated by "<%= template_name + " custom pre" %>"
+<%= snippet_if_exists(template_name + " custom pre") %>
+%end
+
+# copy %pre log files into chroot
+%post --nochroot
+cp -vf /tmp/*pre*log /tmp/sysimage/root/
+%end
+
 %post
 <%= snippet 'redhat_register' %>
 rm -f /etc/ostree/remotes.d/*.conf
 <%= snippet('remote_execution_ssh_keys') %>
 <%= snippet 'efibootmgr_netboot' %>
-(
-# Report success back to Foreman
-<%= snippet 'built' %>
-) 2>&1 | tee /mnt/sysimage/root/install.post.log
+touch /tmp/foreman_built
+%end
 
-exit 0
+%post --log=/root/install.post.custom.log
+# Custom post snippet generated by "<%= template_name + " custom post" %>"
+<%= snippet_if_exists(template_name + " custom post") %>
+%end
 
+<%#
+The last post section halts Anaconda to prevent endless loop in case HTTP request fails
+%>
+<% if (is_fedora && os_major < 20) || (rhel_compatible && os_major < 7) -%>
+%post
+<% else -%>
+%post --erroronfail
+<% end -%>
+if test -f /tmp/foreman_built; then
+  echo "calling home: build is done!"
+  <%= indent(2, skip1: true) { snippet('built', :variables => { :endpoint => 'built', :method => 'POST', :body_file => '/root/install.post.log' }) } -%>
+else
+  echo "calling home: build failed!"
+  <%= indent(2, skip1: true) { snippet('built', :variables => { :endpoint => 'failed', :method => 'POST', :body_file => '/root/install.post.log' }) } -%>
+fi
+
+sync
 %end
