Fixes #32655 - Registration - Missing '/etc/os-release' file
Registration process should exit when `/etc/os-release` file is not found

diff --git a/app/views/unattended/provisioning_templates/registration/global_registration.erb b/app/views/unattended/provisioning_templates/registration/global_registration.erb
--- a/app/views/unattended/provisioning_templates/registration/global_registration.erb
+++ b/app/views/unattended/provisioning_templates/registration/global_registration.erb
@@ -34,6 +34,9 @@ fi
 
 if [ -f /etc/os-release ] ; then
   . /etc/os-release
+else
+  echo "'/etc/os-release' file not found"
+  exit 1
 fi
 
 SSL_CA_CERT=$(mktemp)
