Fixes #38569 - improves error handling while updating built status

diff --git a/app/views/unattended/provisioning_templates/snippet/built.erb b/app/views/unattended/provisioning_templates/snippet/built.erb
--- a/app/views/unattended/provisioning_templates/snippet/built.erb
+++ b/app/views/unattended/provisioning_templates/snippet/built.erb
@@ -39,13 +39,19 @@ EOF
 -%>
 <% end -%>
 if [ -x /usr/bin/curl ]; then
-  /usr/bin/curl -o /dev/null <%= curl_opts.join(' ') %> --silent '<%= url %>'
+  /usr/bin/curl -o /dev/null <%= curl_opts.join(' ') %> --silent --show-error '<%= url %>'
 elif [ -x /usr/bin/wget ]; then
   /usr/bin/wget -q -O /dev/null --method <%= method %> <%= wget_opts.join(' ') %> '<%= url %>'
 else
   wget -q -O /dev/null --header 'Content-Type: text/plain' '<%= url %>'
 fi
 
-if [ -x "$(command -v subscription-manager)" ] ; then
-  subscription-manager facts --update
+if [[ $? == 0  ]] ; then
+  echo "Host [<%= @host.name %>] successfully configured."
+  if [ -x "$(command -v subscription-manager)" ] ; then
+    subscription-manager facts --update
+  fi
+else
+  echo "Failed to set built status for host [<%= @host.name %>]."
 fi
+
