fixes #2516 - dbmigrate changes for SCL

diff --git a/extras/dbmigrate b/extras/dbmigrate
--- a/extras/dbmigrate
+++ b/extras/dbmigrate
@@ -1,10 +1,17 @@
 #!/bin/sh
 USERNAME=$(/usr/bin/id -un)
 WANTED_USER=${1:-'foreman'}
+RAKE_CMD=/usr/bin/rake
+BUNDLER_CMD=""
+
+die() {
+  echo $*; exit 1
+}
 
 if [ $USERNAME = $WANTED_USER ]; then
-  cd && bundle exec /usr/bin/rake db:migrate RAILS_ENV=production
+  cd || die "Cannot change to home directory"
+  [ -f Gemfile ] && BUNDLER_CMD="bundle exec"
+  $BUNDLER_CMD $RAKE_CMD db:migrate RAILS_ENV=production
 else
-  echo "$0 has to be run as user ${WANTED_USER}!"
-  exit 1
+  die "$0 has to be run as user ${WANTED_USER}!"
 fi
